# SPDX-FileCopyrightText: 2026 conpty-oxide contributors <https://github.com/P4suta/conpty-oxide/graphs/contributors>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

style = "conventional"
subject_capitalized = false
subject_length = 0
line_length = 0
